server:
  port: 11111
  servlet:
    context-path: "/api/v1" #Restful统一url前缀


spring:
  datasource:
    driver-class-name: ${database.driver}
    username: ${database.username}
    password: ${database.password}
    url: ${database.url}
  messages:
    basename: i18n/messages #国际化支持
    encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath\:/mybatis-mappers/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false

endpoints:
  enabled: false
  health:
    enabled: true
    time-to-live: 10000
  info:
    enabled: true